.\" Manpage for joke
.TH man 1 "30 October 2019" "1.0" "joke man page"
.SH NAME
joke - humorous command to brighten up your day by telling you joke(s)
.SH SYNOPSIS 
joke 
.B [-a] [-h] [-n 
number
.B ]
.SH DESCRIPTION
By default the command will print a random joke
.PP
.IP -a
Display all jokes.
.IP -h
Displays the manual page
.IP "-n number"
Displays a specific joke identified by a number (starting from 1)
.SH BUGS
No known bugs.
.SH AUTHOR
Jonas Schaefer (https://github.com/j0ner0n)
